In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("all_data.csv")
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,176558,USB-C Charging Cable,2,11.95,04/19/19 08:46,"917 1st St, Dallas, TX 75001"
1,176559,Bose SoundSport Headphones,1,99.99,04-07-2019 22:30,"682 Chestnut St, Boston, MA 02215"
2,176560,Google Phone,1,600,04-12-2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
3,176560,Wired Headphones,1,11.99,04-12-2019 14:38,"669 Spruce St, Los Angeles, CA 90001"
4,176561,Wired Headphones,1,11.99,04/30/19 09:27,"333 8th St, Los Angeles, CA 90001"

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 560549 entries, 0 to 560548
Data columns (total 6 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          558914 non-null  str
 1   Product           558914 non-null  str
 2   Quantity Ordered  558914 non-null  str
 3   Price Each        558914 non-null  str
 4   Order Date        558914 non-null  str
 5   Purchase Address  558914 non-null  str
dtypes: str(6)
memory usage: 25.7 MB

In [4]:
df = df.dropna(how='all')

In [5]:
df = df[df['Product'].notna()]

In [6]:
df = df[df['Order ID'] != 'Order ID']

In [7]:
df['Quantity Ordered'] = pd.to_numeric(df['Quantity Ordered'])
df['Price Each'] = pd.to_numeric(df['Price Each'])

In [11]:
df['Order Date'] = pd.to_datetime(df['Order Date'])

In [12]:
df['Sales'] = df['Quantity Ordered'] * df['Price Each']

In [13]:
df['Month'] = df['Order Date'].dt.month

In [14]:
df['Hour'] = df['Order Date'].dt.hour

In [15]:
df['City'] = df['Purchase Address'].apply(lambda x: x.split(',')[1])

In [16]:
df.info()
df.head()
df.describe()

<class 'pandas.DataFrame'>
Index: 557849 entries, 0 to 560548
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Order ID          557849 non-null  str
 1   Product           557849 non-null  str
 2   Quantity Ordered  557849 non-null  int64
 3   Price Each        557849 non-null  float64
 4   Order Date        557849 non-null  datetime64[us]
 5   Purchase Address  557849 non-null  str
 6   Sales             557849 non-null  float64
 7   Month             557849 non-null  int32
 8   Hour              557849 non-null  int32
 9   City              557849 non-null  str
dtypes: datetime64[us](1), float64(2), int32(2), int64(1), str(4)
memory usage: 42.6 MB

,Quantity Ordered,Price Each,Order Date,Sales,Month,Hour
count,557849.000000,557849.000000,557849,557849.000000,557849.000000,557849.000000
mean,1.124383,184.399886,2019-07-18 21:54:54.752451,185.491070,7.059145,14.413311
min,1.000000,2.990000,2019-01-01 03:07:00,2.990000,1.000000,0.000000
25%,1.000000,11.950000,2019-04-16 21:05:00,11.950000,4.000000,11.000000
50%,1.000000,14.950000,2019-07-17 20:43:00,14.950000,7.000000,15.000000
75%,1.000000,150.000000,2019-10-26 08:14:00,150.000000,10.000000,19.000000
max,9.000000,1700.000000,2020-01-01 05:13:00,3400.000000,12.000000,23.000000
std,0.442792,332.731012,NaN,332.919453,3.502990,5.423409

In [17]:
df.to_csv("cleaned_sales_data.csv", index=False)

In [18]:
df.columns

Index(['Order ID', 'Product', 'Quantity Ordered', 'Price Each', 'Order Date',
       'Purchase Address', 'Sales', 'Month', 'Hour', 'City'],
      dtype='str')

In [19]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Sales,Month,Hour,City
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,"917 1st St, Dallas, TX 75001",23.90,4,8,Dallas
1,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,"682 Chestnut St, Boston, MA 02215",99.99,4,22,Boston
2,176560,Google Phone,1,600.00,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001",600.00,4,14,Los Angeles
3,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001",11.99,4,14,Los Angeles
4,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,"333 8th St, Los Angeles, CA 90001",11.99,4,9,Los Angeles

In [20]:
df['State'] = df['Purchase Address'].apply(lambda x: x.split(',')[2].split(' ')[1])

In [21]:
df.head()

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address,Sales,Month,Hour,City,State
0,176558,USB-C Charging Cable,2,11.95,2019-04-19 08:46:00,"917 1st St, Dallas, TX 75001",23.90,4,8,Dallas,TX
1,176559,Bose SoundSport Headphones,1,99.99,2019-04-07 22:30:00,"682 Chestnut St, Boston, MA 02215",99.99,4,22,Boston,MA
2,176560,Google Phone,1,600.00,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001",600.00,4,14,Los Angeles,CA
3,176560,Wired Headphones,1,11.99,2019-04-12 14:38:00,"669 Spruce St, Los Angeles, CA 90001",11.99,4,14,Los Angeles,CA
4,176561,Wired Headphones,1,11.99,2019-04-30 09:27:00,"333 8th St, Los Angeles, CA 90001",11.99,4,9,Los Angeles,CA

In [22]:
df.to_csv("cleaned_sales_dataset.csv", index=False)